# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 掘金日常任务

on:
  schedule:
    # 书写格式 https://crontab.guru/
    - cron: '50 22 * * *'
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - run: |
          echo "ACTIONS_ALLOW_UNSECURE_COMMANDS=true" >> $GITHUB_ENV
      - run: |
          echo "GOOGLE_CHROME_PATH=$(which google-chrome)" >> $GITHUB_ENV
      - uses: actions/checkout@v4
      - name: 安装PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: 安装依赖
        run: pnpm install
      - name: 转换typescript文件
        run: pnpm build
      - name: 开始执行任务
        env:
          JUEJIN_COOKIE: ${{ secrets.JUEJIN_COOKIE }}
        run: node ./dist/main.js
